name:                dbfield
version:             0.2.0.0
github:              "jappeace/dbfield"
license:             BSD3
author:              "Jappie Klooster"
maintainer:          "jappieklooster@hotmail.com"
copyright:           "2018 Jappie Klooster"
category: Network
synopsis: "A newtype for wrapping newtypes into beam schemas"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/network-uri-lenses#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - beam-core
    - lens
    - beam-migrate
    - postgresql-simple
