name:                beam-newtype-field
version:             0.3.0.0
github:              "jappeace/dbfield"
license:             MIT
author:              "Jappie Klooster"
maintainer:          "jappieklooster@hotmail.com"
copyright:           "2018 Jappie Klooster"
category: Database
synopsis: "A newtype for wrapping newtypes into beam schemas"
description:         Please see the README on GitHub at <https://github.com/jappeace/dbfield#readme>

extra-source-files:
- Readme.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - lens
    - postgresql-simple
    - postgresql-simple >=0.5 && <0.7
    - beam-core >=0.8 && <0.9
    - beam-migrate >=0.4 && <0.5
